<meta content="Central New Jersey .NET User Group" name="description" />
<meta content=".NET, User Group, Princeton, NJ, New Jersey" name="keywords" />
<meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />

<link href="css/common.css" rel="stylesheet" type="text/css" />
<link rel="alternate" type="application/rss+xml" title="Upcoming Events Feed" href="http://feeds.feedburner.com/njdotnet" />

<script src="scripts/jquery-1.6.2.min.js" type="text/javascript"></script>
<script src="scripts/jQuery.tmpl.min.js" type="text/javascript"></script>
<script src="scripts/date.js" type="text/javascript"></script>
<script src="scripts/mailchimp.js" type="text/javascript"></script>
<script src="scripts/urlEncode.js" type="text/javascript"></script>
<script src="scripts/site.js" type="text/javascript"></script>
