<!-- navigation -->
<div style="background-color: #d3d3d3; padding: 5px; padding-left: 22px; font-weight: bold;border-style: solid; border-width: 0px; border-bottom-width: 2px; border-color: #bbbbbb;">
  
    <span><a style="color: black; text-decoration: none;" href="index.html">Home</a></span>
    | <span><a style="color: black; text-decoration: none;" href="meetings.html">Meetings</a></span>
    | <span><a style="color: black; text-decoration: none;" href="directions.html">Directions</a></span>
  <div style="display:inline; float: right; font-style: italic; font-weight:normal; text-align:right; margin-right: 30px;">Come to meet, stay to learn</div>
</div>
