<div class="CommonSidebarArea">
    <h4 class="CommonSidebarHeader">Find Us</h4>
    <div class="CommonSidebarContent">
        <div style="text-align: center;">
            <p>
                <a href="http://twitter.com/njdotnet" target="_blank" style="text-decoration: none;">
                    <img style="border: 0" src="images/twitter_logo_header.png" /></a></p>
            <p>
                <a href="http://www.facebook.com/pages/Njdotnet-Central-NJ-NET-User-Group/108704889187733?v=wall" target="_blank" style="text-decoration: none;">
                    <img style="border: 0" src="images/facebook.jpg" /></a></p>
            <p>
                <a href="http://www.linkedin.com/groups?home=&gid=114719" target="_blank" style="text-decoration: none;">
                    <img style="border: 0" src="images/badge-linkedin.gif" /></a></p>
            <p>
                <a href="http://feeds.feedburner.com/njdotnet"  target="_blank" style="text-decoration: none;">
                    <img style="border: 0; text-align: center;" src="images/rss.png" /><br />
                    Subscribe to our feed!</a></p>
        </div>
    </div>
</div>