<div class="CommonSidebarArea">
    <h4 class="CommonSidebarHeader">Community Megaphone</h4>
    <div class="CommonSidebarContent">
        <div style="text-align: center;">
            <iframe src="http://www.communitymegaphone.com/eventsmini.aspx?PageSize=5&bgcolor=%23fff&forecolor=%23000&filter=(eventtype+%3d+%2527CC%2527+OR+eventtype+%3d+%2527CO%2527+OR+eventtype+%3d+%2527FS%2527+OR+eventtype+%3d+%2527GD%2527+OR+eventtype+%3d+%2527GC%2527+OR+eventtype+%3d+%2527HL%2527+OR+eventtype+%3d+%2527ME%2527+OR+eventtype+%3d+%2527RS%2527+OR+eventtype+%3d+%2527UG%2527+OR+eventtype+%3d+%2527OT%2527)+AND+(State+%3d+%2527NJ%2527+OR+State+%3d+%2527PA%2527)&TextAlign=Center" frameborder='0' scrolling='no' width='160' height='315'></iframe>
        </div>
    </div>
</div>
