<!-- navigation -->
<div style="background-color: #d3d3d3; padding: 5px; padding-left: 22px; font-weight: bold;border-style: solid; border-width: 0px; border-bottom-width: 2px; border-color: #bbbbbb;">
  
    <span><a style="color: black; text-decoration: none;" href="default.aspx">Home</a></span>
    | <span><a style="color: black; text-decoration: none;" href="meetings.aspx">Meetings</a></span>
    | <span><a style="color: black; text-decoration: none;" href="directions.aspx">Directions</a></span>

<!--  Commented out until we update them
                | <span><a style="color: black; text-decoration: none;" href="/sponsorship.aspx">Sponsorship</a></span>
                | <span><a style="color: black; text-decoration: none;" href="/about.aspx">About Us</a></span>
-->
  <div style="display:inline; float: right; font-style: italic; font-weight:normal; text-align:right; margin-right: 30px;">Come to meet, stay to learn</div>
</div>
